// Generated by https://quicktype.io

class CharacterModel {
  CharacterModel({
    this.info,
    this.results,
  });

  Info? info;
  List<Result>? results;

  factory CharacterModel.fromMap(Map<String, dynamic> map){
    return CharacterModel(
      info: Info.fromMap(map['info']),
      results: List<Result>.from(map['results'].map((x) => Result.fromMap(x))),
    );
  }
}

class Info {
  Info({
    this.next,
    this.prev,
    this.pages,
  });

  String? next;
  String? prev;
  int? pages;

  factory Info.fromMap(Map<String, dynamic> map){
    return Info(
      next: map['next'],
      prev: map['prev'],
      pages: map['pages'],
    );
  }
}

class Result {
  Result({
    this.id,
    this.name,
    this.status,
    this.species,
    this.type,
    this.gender,
    this.origin,
    this.location,
    this.image,
    this.episode,
    this.url,
  });

  int? id;
  String? name;
  String? status;
  String? species;
  String? type;
  String? gender;
  Location? origin;
  Location? location;
  String? image;
  List<dynamic>? episode;
  String? url;

  factory Result.fromMap(Map<String, dynamic> map){
    return Result(
      id: map['id'],
      name: map['name'],
      status: map['status'],
      species: map['species'],
      type: map['type'],
      gender: map['gender'],
      origin: Location.fromMap(map['origin']),
      location: Location.fromMap(map['location']),
      image: map['image'],
      episode: map['episode'],
      url: map['url'],
    );
  }
}


class Location {
  Location({
    this.name,
    this.url,
  });

  String? name;
  String? url;

  factory Location.fromMap(Map<String, dynamic> map){
    return Location(
      name: map['name'],
      url: map['url'],
    );
  }
}