// Generated by https://quicktype.io
class LocationModel {
  LocationModel({
    this.info,
    this.results,
  });

  Info? info;
  List<Result>? results;

  factory LocationModel.fromMap(Map<String, dynamic> map){
    return LocationModel(
      info: Info.fromMap(map['info']),
      results: List<Result>.from(map['results'].map((x) => Result.fromMap(x))),
    );
  }
}

class Info {
  Info({
    this.next,
    this.prev,
  });

  String? next;
  String? prev;

  factory Info.fromMap(Map<String, dynamic> map){
    return Info(
      next: map['next'],
      prev: map['prev'],
    );
  }
}

class Result {
  Result({
    this.id,
    this.name,
    this.type,
    this.dimension,
    this.residents,
    this.url,
  });

  int? id;
  String? name;
  String? type;
  String? dimension;
  List<String>? residents;
  String? url;

  factory Result.fromMap(Map<String, dynamic> map){
    return Result(
      id: map['id'],
      name: map['name'],
      type: map['type'],
      dimension: map['dimension'],
      residents: List<String>.from(map['residents']),
      url: map['url'],
    );
  }
}
